version: '3.8'

services:
  backend:
    build: ./app/
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app  # Для разработки - монтируем код

  frontend:
    container_name: frontend_accounting
    build: ./frontend/
    volumes:
      - ./frontend:/app/frontend

    command: sh -c "npm install && npm run dev"
