version: '3.8'

services:
  backend:
    container_name: backend_accounting
    build: ./backend/
    ports:
      - "8000:8000"
    volumes:
      - static:/app/static

  frontend:
    container_name: frontend_accounting
    build: ./frontend/
    volumes:
      - static:/frontend/dist

  gateway:
    container_name: gateway_accounting
    build: ./gateway
    ports:
      - 8000:80
    volumes:
      - static:/static

volumes:
  static:
