version: '3.8'

services:
  backend:
    container_name: backend_accounting
    build: ./backend/
    volumes:
      - static:/app/static
    networks:
      - app_network

  frontend:
    container_name: frontend_accounting
    build: ./frontend/
    volumes:
      - static:/frontend/dist
    networks:
      - app_network

  gateway:
    container_name: gateway_accounting
    build: ./gateway
    ports:
      - 80:80
    volumes:
      - static:/var/www/static
    depends_on:
      - backend
      - frontend
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
volumes:
  static:
